services:

  web_lospatitos:
    image: php:7.4-apache
    container_name: web_lospatitos
    hostname: web_lospatitos
    restart: always
    environment:
      DB_HOST: db_lospatitos
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      DB_NAME: $MYSQL_DATABASE
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html
    networks:
      - net_isw811

  db_lospatitos:
    image: mysql:8.0
    container_name: db_lospatitos
    hostname: db_lospatitos
    restart: always
    env_file: .env
    volumes:
      - vol_lospatitos:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - net_isw811

volumes:
  vol_lospatitos:

networks:
  net_isw811:
    external: true